# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Varun Turlapati
description: >- # this means to ignore newlines until "baseurl:"
  A meet and greet page with info about me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: varunturlapati
github_username:  varunturlapati
medium_url: https://medium.com/@varunturlapati
linkedin_url: https://www.linkedin.com/in/varunturlapati
technical_resume_title: Varun Turlapati's technical resume
investments:
  syndicate_url: https://angel.co/chaanakya/syndicate
  syndicate_name: Chaanakya
  syndicate_description: >-
    We are looking to back companies in the sapces of FoodTech, AgTech, Conservation, EdTech, Mass Tranit, Clean Energy, CleanTech, Inclusivity
  partners:
    javacapital:
      site: https://www.javacapital.co/
    portfolia:
      site: https://www.portfolia.co/
  personal:
    companies:
      accessiblego:
        twitter: accessibleGo
        site: https://accessiblego.com/
      languagelearning:
        site: https://languagelearningmarket.com/about-us/
        linkedin: 40696623
      patchr:
        site: https://patchr.io/
      psyonic:
        twitter: PSYONICinc
        site: https://www.psyonic.io/
        youtube: UCAuEvRfpMDCqtGL0cuVbmyA/featured
languages:
  wiki_base_url: https://en.wikipedia.org/wiki/
  telugu: Telugu_Language
  marathi: Marathi_Language
  hindi: Hindi_Language
  kannada: Kannada_Language
  english: English_Language
  spanish: Spanish_Language
  mandarin: Mandarin_Language
social:
  twitter: https://www.twitter.com/
  youtube: https://www.youtube.com/channel/
  linkedin: https://www.linkedin.com/company/
colors:
  purple: 5404A4
  yellow: F6E820


# Build settings
#theme: minima
#plugins:
#  - jekyll-feed

# Remote theme
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
